### ISSUE TITLE
Reference to 1.7.4-alpha-37 is incorrect

### ISSUE THREAD

**Issue by engineers-tools** [NetOfficeFw/Samples#5]
When trying to build this project I get an error which says that version "1.7.4-alpha-37" could not be found. The version available on NuGet under 'prerelease' is "1.7.4-pre-jun-28-2015"

**Comment by jozefizso** [comment]
The 1.7.4-alpha pre-release packages are from [netofficefw-dev](https://www.myget.org/feed/Packages/netofficefw-dev) feed. This feed is set in `NuGet.config` file so NuGet should be able to find it.

Which sample is not working?

**Comment by jozefizso** [comment]
I see, the Excel samples are using 1.7.4-alpha package and the exact version was deleted by retention policies. I will update samples.

**Comment by jozefizso** [comment]
It should work now (commit baa093c851a581f4c0e207d02cb5dca0328b6ccc)

**Comment by engineers-tools** [comment]
All good. Thank you for the quick fix and a great project.
