### ISSUE TITLE
Excel Example package "1.7.4.1-pre1"

### ISSUE THREAD

**Issue by TelcoPhil** [NetOfficeFw/Samples#6]
HI,
I downloaded your examples and VS tells me that the packages references (e.g. Core, Excel) are not available.
Packages.Config shows that the exapmle wants ""1.7.4.1-pre1" for both, which are not available...
Thanks for all your work!

**Comment by jozefizso** [comment]
Sample are update to **NetOffice 1.7.4.5**

**Comment by jozefizso** [comment]
Should be fixed now.
